In [1]:
%matplotlib notebook

import numpy as np
import matplotlib.tri as tri
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import matplotlib
from matplotlib import cm

def make_map(projection=ccrs.PlateCarree()):
    
    fig, ax = plt.subplots(figsize=(6, 6),
                           subplot_kw=dict(projection=projection))
#     gl = ax.gridlines(draw_labels=True)
#     gl.xlabels_top = gl.ylabels_right = False
#     gl.xformatter = LONGITUDE_FORMATTER
#     gl.yformatter = LATITUDE_FORMATTER
    return fig, ax

def plot_gtiff(ax, data, transform, cmap='viridis', vmin=None, vmax=None, cbar=False, cbar_kwargs={}, **kwargs):
    extent = plot_extent(data, transform)
    im = ax.imshow(data, extent=extent, vmin=vmin, vmax=vmax, cmap=cmap, origin='upper', **kwargs)
    ax.set_extent(extent)
    
    dmin, dmax = np.nanmin(data), np.nanmax(data)
    vmin = vmin if vmin is not None else dmin 
    vmax = vmax if vmax is not None else dmax
    if (dmax > vmax) and (dmin < vmin):
        cbar_kwargs.update(extend='both')
    elif dmax > vmax:
        cbar_kwargs.update(extend='max')
    elif dmin < vmin:
        cbar_kwargs.update(extend='min')

    if cbar:
        cbar = set_colorbar(ax, im, **cbar_kwargs)
    else:
        cbar = None
    return im, cbar

def plot_extent(data, transform):
    rows, cols = data.shape[-2:]
    left, top = transform * (0, 0)
    right, bottom = transform * (cols, rows)
    extent = (left, right, bottom, top)
    return extent

In [2]:
import glofrim.gbmi_lib as glib 
from configparser import ConfigParser
from os.path import join, isfile, abspath, dirname, basename, normpath

In [3]:
# config_fn = r'/home/dirk/repos/model_test_data/test_Elbe/glofrim_PCR2CMF.ini'
config_fn = r'/home/dirk/repos/model_test_data/test_Elbe/glofrim_PCR2DFM.ini'
# config_fn = r'/home/dirk/repos/model_test_data/test_Elbe/glofrim_WFL2DFM.ini'
env_fn = r'/home/dirk/repos/glofrim/environment.ini'

In [4]:
# _cf = ConfigParser(inline_comment_prefixes=('#'))
# env = glib.configread(abspath(env_fn), encoding='utf-8', cf=_cf)
# glib.config2dict(env)

In [5]:
from glofrim import Glofrim
cbmi = Glofrim()
cbmi.initialize_config(config_fn, env_fn=env_fn)
cbmi.exchanges

2018-07-20 14:09:13,969 - PCR - INFO - Config initialized
2018-07-20 14:09:13,991 - DFM - INFO - Config initialized


[('update', 'PCR'),
 ('exchange',
  {'coupling': SpatialCoupling object from PCR to DFM based on grid_2_1d method,
   'from_mod': 'PCR',
   'from_unit': ['m/day', 'm2'],
   'from_vars': ['runoff', 'cellArea'],
   'to_mod': u'DFM',
   'to_unit': ['mm', 'm2', 'unknown'],
   'to_vars': [u'rain', u'ba', 1000.0]}),
 ('exchange',
  {'add': True,
   'coupling': SpatialCoupling object from PCR to DFM based on grid_us_2_1d_us method,
   'from_mod': 'PCR',
   'from_unit': ['m3/s', 'unknown'],
   'from_vars': ['discharge', 86400.0],
   'to_mod': u'DFM',
   'to_unit': ['mm', 'm2', 'unknown'],
   'to_vars': [u'rain', u'ba', 1000.0]}),
 ('update', 'DFM')]

In [6]:
# config_fn = r'/home/dirk/repos/model_test_data/test_Elbe/WFL_Elbe/SBM/wflow_sbm.ini'
# cbmi.bmimodels['WFL']._bmi.initialize_config(config_fn)
# cbmi.bmimodels['WFL']._bmi.dynModel.clonemappath

In [7]:
# cbmi.set_out_dir()

In [8]:
cbmi.initialize_model()

2018-07-20 14:09:14,215 - DFM - WARNING - /home/dirk/repos/model_test_data/test_Elbe/DFM_Elbe/Elbe_1way_1d2dFM_400m_3200m_glofrim.mdu file overwritten
2018-07-20 14:09:14,225 - DFM - INFO - Ini file written to /home/dirk/repos/model_test_data/test_Elbe/DFM_Elbe/Elbe_1way_1d2dFM_400m_3200m_glofrim.mdu
2018-07-20 14:09:25,560 - DFM - INFO - Model initialized
2018-07-20 14:09:25,561 - PCR - INFO - Getting rgrid info based on landmask_elbe_30min.map
2018-07-20 14:09:25,565 - PCR - INFO - Getting drainage direction from ldd_elbe_30min.map
2018-07-20 14:09:25,567 - DFM - INFO - Getting DFM UGrid.


1D nodes found outside of valid 2D domain
1D nodes found outside of valid 2D domain


2018-07-20 14:09:26,270 - PCR - WARNING - /home/dirk/repos/model_test_data/test_Elbe/PCR_Elbe/setup_PCR_30min_Elbe_glofrim.ini file overwritten
2018-07-20 14:09:26,273 - PCR - INFO - Ini file written to /home/dirk/repos/model_test_data/test_Elbe/PCR_Elbe/setup_PCR_30min_Elbe_glofrim.ini
2018-07-20 14:09:26,280 pcrglobwb_bmi_v203.configuration INFO Model run started at 2018-07-20 14:09:26.274699
2018-07-20 14:09:26,281 pcrglobwb_bmi_v203.configuration INFO Logging output to /home/dirk/Experiments/glofrim/test_Elbe/PCR/log/setup_PCR_30min_Elbe.ini_2018-07-20T14:09:26.274699.log
2018-07-20 14:09:26,282 pcrglobwb_bmi_v203.configuration INFO Note that avgSurfaceWaterInputLongIni is not used and not needed.
2018-07-20 14:09:26,284 pcrglobwb_bmi_v203.configuration INFO The initial condition "subDischargeIni" is not defined. Either "avgDischargeShortIni" or "avgDischargeLongIni" is used in this run. Note that the "subDischargeIni" is only relevant if kinematic wave approaches are used.
2018-07

In [9]:
import numpy as np
c1 = cbmi.exchanges[2][1]['coupling'] 
c1.set_frac()
c1.to_ind.shape, c1.from_ind.shape, c1.frac.shape

((1136,), (9,), (1136,))

In [10]:
# model coupled indices
c1.to_ind, c1.from_ind

(array([6863, 6864, 6865, ..., 7304, 7305, 6628], dtype=int32),
 array([154, 155, 127, 170, 148, 169, 171, 172, 153], dtype=int32))

In [11]:
# labels for coupled indices
c1.to_grp, c1.from_grp

(array([0, 0, 0, ..., 5, 5, 6]), array([0, 1, 2, 3, 4, 4, 5, 5, 6]))

In [12]:
# n:n coupling
c1.to_grp_n, c1.from_grp_n

(array([293, 297,  78, 239, 149,  79,   1]), array([1, 1, 1, 1, 2, 2, 1]))

In [13]:
# fraction
c1.frac[c1.to_grp==0].sum()

0.9999999999999997

In [14]:
# fcoords = c1.to_bmi.grid.get_poly_coords()
# fpatches = (matplotlib.patches.Polygon(face) for face in fcoords)
# fpc = matplotlib.collections.PatchCollection(fpatches, edgecolor='blue')
# fpc.set_facecolor('none')

In [15]:
# fig, ax = make_map()
# # grid cells
# cells = c1.from_bmi.grid.get_poly_coords()
# gpatches = (matplotlib.patches.Polygon(cell) for cell in cells)
# gpc = matplotlib.collections.PatchCollection(gpatches, edgecolor='grey')
# gpc.set_facecolor('none')
# # color linked cells
# g = np.ma.masked_equal(np.zeros(c1.from_bmi.grid.shape), 0)
# g.flat[c1.from_ind] = c1.from_grp
# # all nodes
# n = c1.to_bmi.grid._1d.nodes
# ax.add_collection(gpc)
# # ax.add_collection(fpc)
# plot_gtiff(ax, g, c1.from_bmi.grid.transform, cmap=cm.tab20)
# ax.scatter(n[:,0], n[:,1], c='grey', s=0.1)
# ax.scatter(n[c1.to_ind,0], n[c1.to_ind,1], c=c1.to_grp, s=2, cmap=cm.tab20)

In [16]:
y, x =  53.5267, 9.9535
pcr_idx = cbmi.index(x,y, 'PCR'), 
dfm_idx = cbmi.index(x,y, 'DFM', in1d=True)
# check
cbmi.bmimodels['DFM'].grid._1d.xy(pcr_idx), cbmi.bmimodels['PCR'].grid.xy(dfm_idx)

NameError: global name 'inds' is not defined

In [ ]:
cbmi.get_start_time(), cbmi.get_current_time(), cbmi.get_end_time(), cbmi.get_time_step()

In [ ]:
from datetime import datetime
cbmi.update_until(datetime(2000, 1, 10))
cbmi.get_current_time()

In [ ]:
# cbmi.finalize()